version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
